version: '3'
services:
  postgres:
    container_name: postgresdb
    network_mode: bridge
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      -  postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pin-manager:
    container_name: pin-manager-app
    network_mode: bridge
    image: pin-manager
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  postgres-data: